DROP DATABASE IF EXISTS grownup;

CREATE DATABASE grownup;

USE grownup;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL,
    password VARCHAR(100) NOT NULL,
    score INT DEFAULT 0,
    PRIMARY KEY (id),
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL


);

CREATE TABLE IF NOT EXISTS  topics (
    id INT AUTO_INCREMENT,
    user_id INT,
    title  VARCHAR(200) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS  posts (
    id INT AUTO_INCREMENT,
    title VARCHAR(200) NOT NULL,
    body VARCHAR(1000) NOT NULL,
    user_id INT,
    topic_id INT,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    score INT DEFAULT 0,
    PRIMARY KEY (id, user_id, topic_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS  comments (
    id INT AUTO_INCREMENT,
    body VARCHAR(3000) NOT NULL,
    user_id INT,
    post_id INT,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP NOT NULL,
    PRIMARY KEY (id, user_id, post_id),
    FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS tags (
    id INT AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP  NOT NULL,
    PRIMARY KEY (id)

);

CREATE TABLE IF NOT EXISTS votes (
user_id INT,
post_id INT,
vote INT,
PRIMARY KEY (user_id, post_id),
FOREIGN KEY (post_id) references posts (id),
FOREIGN KEY (user_id) references users (id)

);

